apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k8s-metallb-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.10.20.201-10.10.20.255  # Reserve IP range for LoadBalancer services
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - k8s-metallb-ip-pool
