apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-apache-ingress
spec:
  ingressClassName: nginx    # 👈 Must match the IngressClass name
  rules:
  - host: web-app-apache.__DOMAIN__
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-app-apache
            port:
              number: 80
