apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-alma-yum-server
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: lab-infra-nfs
  resources:
    requests:
      storage: 1Mi
  volumeName: pv-alma-yum-server
